// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------- //
// modulation //
// ---------- //

#define modulation_wrap_target 0
#define modulation_wrap 3
#define modulation_pio_version 0

static const uint16_t modulation_program_instructions[] = {
            //     .wrap_target
    0x2016, //  0: wait   0 gpio, 22
    0x6004, //  1: out    pins, 4
    0x2096, //  2: wait   1 gpio, 22
    0x6004, //  3: out    pins, 4
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program modulation_program = {
    .instructions = modulation_program_instructions,
    .length = 4,
    .origin = -1,
    .pio_version = modulation_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x2
#endif
};

static inline pio_sm_config modulation_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + modulation_wrap_target, offset + modulation_wrap);
    return c;
}
#endif
